#
#  Makefile for the kernel Sensor device drivers.
#

# Object files in subdirectories
obj-$(CONFIG_INPUT_YAS_MAGNETOMETER)		+= geomagnetic/
obj-y	+= optical/
obj-$(CONFIG_SENSORS_CORE)		+= sensors_core.o
