obj-$(CONFIG_INSIDESECURE_VPNCLIENT) := vpnclient.o

vpnclient-y := \
	ip_selector_db.o \
	ip_selector_match.o \
	kernelspd_main.o \
	kernelspd_hooks.o \
	kernelspd_procfs.o \
	spd_util.o \
	debug_filter.o \
	debug_strf.o \
	debug_linux.o \
	debug_strbuf_stack.o \

override EXTRA_CFLAGS += \
    -DKERNEL \
    -D_KERNEL \
    -DWITH_IPV6

ifeq ($(DEBUG), 1)
override EXTRA_CFLAGS += \
         -DDEBUG_LIGHT
endif
