GCC_VERSION      := $(shell $(CONFIG_SHELL) $(PWD)/scripts/gcc-version.sh $(CROSS_COMPILE)gcc)
ccflags-y += -Idrivers/media/video/msm_jfactive -Idrivers/media/video/msm/server
obj-$(CONFIG_MSM_CCI) += msm_cci.o
