#ANDROIDROOT=$(PWD)/../../../../android
#KERNELSRC=$(ANDROIDROOT)/kernel
#KERNELOUT=$(ANDROIDROOT)/out/target/product/$(TARGET)/obj/KERNEL_OBJ 
ifeq ($(TIMA_ENABLED),1)
obj-y += checkpower.o
endif
#all:
#	make -C $(KERNELSRC) O=$(KERNELOUT) M=$(PWD) modules

#clean:
#	make -C $(KERNELSRC) O=$(KERNELOUT) M=$(PWD) clean 
